apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: auth-backend
  name: auth-backend
spec:
  type: NodePort
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
      nodePort: 30086
  selector:
    io.kompose.service: auth-backend
