apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 5173        # service port inside cluster
      targetPort: 5173  # container port
      nodePort: 30073   # external port on your machine (must be 30000–32767)