apiVersion: v1
kind: Service
metadata:
  name: image-db
  labels:
    app: image-db
spec:
  selector:
    app: image-db
  ports:
    - port: 3306        # service port inside cluster
      targetPort: 3306  # container port