apiVersion: v1
kind: Service
metadata:
  name: image-backend
  labels:
    app: image-backend
spec:
  type: NodePort
  selector:
    app: image-backend
  ports:
    - name: http
      port: 3000        # service port inside cluster
      targetPort: 3000  # container port
      nodePort: 30084   # external port on your node (pick a free 300xx)