apiVersion: v1
kind: Service
metadata:
  name: search-backend
  labels:
    app: search-backend
spec:
  type: NodePort
  selector:
    app: search-backend
  ports:
    - name: http
      port: 8083        # service port inside cluster
      targetPort: 8083  # containerPort
      nodePort: 30083   # external port on localhost